#################################################
#
#	npc 홍보 설정.
#
#################################################

#################################################
# npc 멘트 딜레이(초단위)
# 몇초마다 멘트 할지 여부.
ment_delay	= 180
# npc멘트
# 멘트 랜덤으로 출력
ment1		= 일반채팅/귓속말/혈맹채팅/전체채팅 현금거래 언급시 경고없이 차단!!!
ment2		= 수배: 1단5만, 2단10만, 3단15만
ment3		= 기란마을만 "경험치지급단"이 지급 됩니다!!!
ment4		= 
ment5		= 버그 악용시 제제(밴,차단) 대상입니다!
ment6		= 신규 혈맹은 57레벨에 자동 탈퇴 됩니다!
ment7		= 
ment8		= 거짓선동, 서버비하 1차 1일채금, 2차 차단
ment9		= 
ment10		= 

#################################################
# 홍보 내용
# 총 10개 가능
# title: 사이트 주소
# content: 사이트 홍보 내용
title1		= 
content1	= 

title2		= 
content2	= 0

title3		= 
content3	= 

title4		= 
content4	= 

title5		= 
content5	= 

title6		= 
content6	= 

title7		= 
content7	= 

title8		= 
content8	= 

title9		= 
content9	= 

title10		= 
content10	= 

#################################################
